version: '3'

services:

  nginx-prod:
    image: ${NGINX_PROD_IMAGE:-nginx:1.13.3-alpine}
    environment:
      VIRTUAL_HOST: ${NGINX_PROD_VIRTUAL_HOST:-lemp.acme.dev, ~^lemp\..*\.xip\.io}
      HTTPS_METHOD: noredirect # support both http and https
      NGINX_PORT: ${PORT}
    working_dir: /opt/app
    command: sh apply-env.sh
    depends_on:
      - app-prod
    links:
      - app-prod
    volumes:
      - ./config/conf.d/default_prod.conf:/etc/nginx/conf.d/default.conf.tpl
      - ./src:/var/www/html
      - ./apply-env.sh:/opt/app/apply-env.sh
    restart: unless-stopped
    network_mode: bridge

  app-prod:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        CI_BUILD_ID: ${CI_BUILD_ID}
        CI_BUILD_REF: ${CI_BUILD_REF}
        CI_BUILD_TIME: ${CI_BUILD_TIME}
        CI_REGISTRY_IMAGE: ${CI_REGISTRY_IMAGE}
    image: ${APP_PROD_IMAGE:-datphan/demp:develop}
    command: sh run-prod.sh
    working_dir: /opt/app
    volumes:
      - ./run-prod.sh:/opt/app/run-prod.sh
    env_file:
      - .env-common
      - .env-prod
    depends_on:
      - db
    links:
      - db
      - nginx-prod
    network_mode: bridge
